CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(255) NOT NULL,
  username VARCHAR(15) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(15) NOT NULL,
  lastName VARCHAR(20) NOT NULL,
  birthDate DATE NOT NULL,
  UNIQUE (username)
);